### ISSUE TITLE
Base Module

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/redhen#50]
- [x] Info file
  - `redhen/redhen.info.yml`
- [x] Routes
  - `redhen/redhen.routing.yml`
- [x] Menu links
  - `redhen/redhen.links.menu.yml`
- [x] Permissions
  - `redhen/redhen.permissions.yml`
- [x] Config schema
  - `redhen/config/schema/redhen.schema.yml`
- [x] Config install (default values)
  - `redhen/config/install/redhen.settings.yml`
- [x] Config form
  - `redhen/src/Form/RedhenAdminSettingsForm.php`
    - Extend ConfigFormBase
- [x] JS / CSS libraries
  - `redhen/redhen.libraries.yml`

**^ < 1 hour**

**Comment by ruscoe** [comment]
JS / CSS libraries yml file should look like this:

```
redhen-forms-js:
  version: 1.x
  js:
    js/redhen.forms.js: {}

redhen-css:
  version: 1.x
  css:
    css/redhen.css: {}
```

Attach the libraries to a render array:

``` php
$content['#attached']['library'][] = 'redhen/redhen-forms-js';
$content['#attached']['library'][] = 'redhen/redhen-css';
```
