### ISSUE TITLE
Connection Role Field Permissions

### ISSUE THREAD

**Issue by tauno** [thinkshout/redhen#67]
- [ ] Alter field configuration to add setting for connection role permissions (probably use [ThirdPartySettingInterface](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Config%21Entity%21ThirdPartySettingsInterface.php/interface/ThirdPartySettingsInterface/8.2.x))
- [ ] Build permission form for field configuration:

```
    [Field]
       [Connection Type]
            Role                       View           Edit
            ----------------------------------------------
            Ed Liason                   X                X
            Parent                      X                
```
- [ ] Implement `hook_entity_field_access_alter()` to make use of the new permissions.

**Comment by tauno** [comment]
Schema ideas:

```
field.field.*.*.*.third_party.redhen_connection_permissions:
  type: mapping
  label: 'RedHen Connection Permissions'
  mapping:  
    connection_types: 
      type: sequence
        [connection_types]
    view: 
      type: sequence
        [roles]
     edit:
       type: sequence
         [roles]
```

```
field.field.*.*.*.third_party.redhen_connection_permissions:
  type: mapping
  label: 'RedHen Connection Permissions'
  mapping:  
  connection type
    view: [roles]
    edit: [roles]
  connection type 2
    view: [roles]
    edit: [roles]
```
